// <auto-generated />
namespace Connect4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class change_NextTurnPlayer_Enum_To_Italian : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_NextTurnPlayer_Enum_To_Italian));
        
        string IMigrationMetadata.Id
        {
            get { return "202206091431381_change_NextTurnPlayer_Enum_To_Italian"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
